config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :cars , only: [:index, :create, :new, :edit, :show, :update, :destroy]
  root to: "home#index" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car
  include Mongoid::Document
  include Mongoid::Timestamps

  field :uuid
  field :brand, type: String
  field :car_model, type: String
  field :description, type: String
  field :picture, type: String

  belongs_to :user

  validates :brand, presence: true
  validates :car_model, presence: true
  validates :description, presence: true
  validates :picture, presence: true
  validates :user_id, presence: true

  before_create do
    set_uuid if uuid.blank?
  end

  private
  def set_uuid
    self.uuid = UUIDTools::UUID.random_create.to_s
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  has_many :cars


  validates :email,
  uniqueness:   true,
  presence:     true
  validates :encrypted_password, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_car, only: %i[ show edit update destroy ]

  # GET /cars or /cars.json
  # find car by User id.
  def index
   @cars = Car.where(:user_id => current_user.id)
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(
      brand: "",
      car_model: "",
      description: "",
      picture: "",
      user: current_user
    )

    @car.save
    
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to car_url(@car), notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to car_url(@car), notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy!

    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:brand, :car_model, :description, :picture)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # GET /cars or /cars.json  
  # GET All Car
  def index
        @cars = Car.all
        render
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
<p>

<strong>Brand:</strong>
<%= car.brand %>
</p>

<strong>Model:</strong>
<%= car.car_model %>
</p>

<p>
<strong>Description:</strong>
<%= car.description %>
</p>

<p>
<%= image_tag car.picture, width: '50%' if car.picture.present? %>
</p>

<p>
<strong>Post By:</strong>
<%= car.user.email %>
</p>


</div>

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
    <div> 
      <%= form.label :brand, style: "display: block" %>
      <%= form.text_field :brand %>
    </div>
  
    <div>
      <%= form.label :car_model, style: "display: block" %>
      <%= form.text_field :car_model %>
    </div>

    <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description %>
    </div>
  
    <div>
      <p>URL Link</p>
      <%= form.label :picture, style: "display: block" %> 
      <%= form.text_field :picture %>
    </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<% content_for :title, "Editing car" %>

<h1>Editing car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Show This Car", @car %> |
  <%= link_to "Back to Home", root_path %>
</div>

app/views/cars/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Your Cars" %>

<h1>Cars</h1>

<% @cars.in_groups_of(4) do |group| %>
  <div class="row text-center">
    <% group.compact.each do |car| %>
      <div class="col-md-4 ">
        <%= image_tag car.picture, width: '50%' if car.picture.present? %>
        <p><%= car.brand %></p>
        <h4><%= link_to car.car_model, car %></h4>
        <p>
          <strong>Post By:</strong>
          <%= car.user.email %>
        </p>
      </div>
    <% end %>
  </div>
<% end %>


<% if user_signed_in? %> 
  <div> Welcome <%= current_user.email %> </div> 

    <p>
      <%= link_to "Post Car", new_car_path %> |
      <%= link_to "Back to Home", root_path %>
    </p>

  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>

app/views/cars/new.html.erb
<% content_for :title, "Post Your Car" %>

<h1>New car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Back to Home", root_path %>
</div>

app/views/cars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @car %>

<div>

  <% if user_signed_in? %> 
    <div> Welcome <%= current_user.email %> </div> 
    <p>
      <%= link_to "Edit This Car", edit_car_path(@car) %> |
      <%= link_to "See Your Cars Post", cars_path %> |
      <%= link_to "Back to home", root_path %>
    </p> 
    <%= button_to "Destroy this car", @car, method: :delete %>
    <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
  <% else %>
    <%= button_to "Back to cars", cars_path %> 
<% end %>

</div>

app/views/home/index.html.erb
<% content_for :title, "All Cars" %>

<h1>Cars</h1>

<% @cars.in_groups_of(4) do |group| %>
  <div class="row text-center">
    <% group.compact.each do |car| %>
      <div class="col-md-4 ">
        <%= image_tag car.picture, width: '50%' if car.picture.present? %>
        <p><%= car.brand %></p>
        <h4><%= link_to car.car_model, car %></h4>
        <p>
          <strong>Post By:</strong>
          <%= car.user.email %>
        </p>
      </div>
    <% end %>
  </div>
<% end %>


<% if user_signed_in? %> 
  <div> Welcome <%= current_user.email %> </div> 
    <p>
      <%= link_to "Post Car", new_car_path %> |
      <%= link_to "See Your Cars Post", cars_path %>
    </p>

  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Show Your Cars" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <nav class="navbar navbar-expand-lg navbar">
    <div class="container">
      <a class="navbar-brand" href="/">Show Your Car</a>
  </div>
</nav>
<body>
<div class="container">
  <%= yield %>
</div>

<body>

  <p class="notice"><%= notice %></p> 
  <p class="alert"><%= alert %></p> 
  </body>
</html>